### ISSUE TITLE
Linux compilation

### ISSUE THREAD

**Issue by jorgefm** [eboasson/i11eperf#1]
Hi,
In order to compile the package under Ubuntu 18.04 I've changed:

`$ git diff src/stats.hpp
diff --git a/src/stats.hpp b/src/stats.hpp
index 941060c..6b80804 100644
--- a/src/stats.hpp
+++ b/src/stats.hpp
@@ -13,9 +13,10 @@
 #define STATS_HPP
 
 #include <iostream>
-#include<fstream>
+#include <fstream>
 #include <iomanip>
 #include <chrono>
+#include <algorithm>
 
 struct tslat {
   double t, l;

And to make it compile against the last OpenDDS:

$ git diff CMakeLists.txt
diff --git a/CMakeLists.txt b/CMakeLists.txt
index 1d7e63d..17beb17 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -160,17 +160,17 @@ endif()
 #     (presumably because it slows down things a bit) it works
 #   - FastDDS with OpenDDS results in "failed to deserialize data payload for SPDP"
 #     errors from OpenDDS
-find_package(opendds QUIET)
+find_package(OpenDDS QUIET)
 if(OPENDDS_FOUND)
   message(STATUS "OpenDDS found")
   add_library(i11eperf_o)
-  set_property(TARGET i11eperf_o PROPERTY CXX_STANDARD 98)
+  #set_property(TARGET i11eperf_o PROPERTY CXX_STANDARD 98)
   OPENDDS_TARGET_SOURCES(i11eperf_o idl/i11eperf.idl)
   target_link_libraries(i11eperf_o OpenDDS::Dcps)
   add_executable(opub src/opub.cpp)
   add_executable(osub src/osub.cpp)
-  set_property(TARGET opub PROPERTY CXX_STANDARD 98)
-  set_property(TARGET osub PROPERTY CXX_STANDARD 98)
+  #set_property(TARGET opub PROPERTY CXX_STANDARD 98)
+  #set_property(TARGET osub PROPERTY CXX_STANDARD 98)
   target_compile_definitions(opub PUBLIC OPENDDS)
   target_compile_definitions(osub PUBLIC OPENDDS)
   target_link_libraries(opub i11eperf_o OpenDDS::OpenDDS)
`

**Comment by eboasson** [comment]
Thanks! I just copied your changes and updated the repository. (I assumed you'd have done a PR if you wanted the commit to be under your name. If am wrong in so assuming, my apologies.)

**Comment by jorgefm** [comment]
It's perfect! Thanks!
